#!/bin/sh
#
# @name Innovair Razorbill SITL
#
# @type Quadrotor Wide
#
# @maintainer Matthew Cole <matthew.cole@innovair.co.uk>
#

set VEHICLE_TYPE mc

if [ $AUTOCNF = yes ]
then
	param set NAV_ACC_RAD 2

	param set RTL_RETURN_ALT 30
	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set PWM_MAX 1950
	param set PWM_MIN 1075
	param set PWM_RATE 400
fi

# 
# Parameters set on prototype setup
#

param set CBRK_IO_SAFETY 22027
param set COM_RC_IN_MODE 1
param set COM_DISARM_PRFLT 200

set GPS_1_CONFIG 0
set ARM_SWISBTN 1

#
# This is the gimbal pass mixer.
#
set MIXER_AUX pass
set PWM_AUX_OUT 1234
set MIXER quad_w

